### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by ratnesh1729** [nwojke/cosine_metric_learning#10]
Thanks for this nice paper and codebase. It is very helpful for comparing,

How does the training time differs and what is the actual training time on your GPU (Mars or Market) ? I am seeing very fast training on Mars < 1 hour.. on 1080 Ti, Mars.

**Comment by nwojke** [comment]
Hi ratnesh1729, I don't remember exact wallclock times but 1-2 hours could be right. What difference are you interested in? MARS and Market? Since the script trains for a fixed number of iterations the training time should be the same of both datasets.

**Comment by nwojke** [comment]
Using a GTX 1080 I get around 11 iterations per seconds at approximately 75% GPU utilization using the default configuration. This would be 152 minutes or 2,5 hours for the full 100k iterations, but the model converges earlier.

**Comment by irisqp** [comment]
> 
> 
> Hi ratnesh1729, I don't remember exact wallclock times but 1-2 hours could be right. What difference are you interested in? MARS and Market? Since the script trains for a fixed number of iterations the training time should be the same of both datasets.

@nwojke,hello ,thanks for your excellent work! As you mentioned here the script trains for a fixed number of iterations, what the exactaly iterations it is , I tried to find this parameter in your code, but couldn't found it. I'm training this model on VeRi in on my GPU(TITAN Xp) for like 10 hours but it seems never gonna stop. So I was wondering maybe somewhere went wrong, meanwhile  I run train_veri.py, when start training, there is no feedback message, like loss, or iterations occur on the screen. but I looked up the GPU usage, it seems like start training. I want know how long it takes to train on VeRi DataSet. Thank you very much.

**Comment by sherlockchou86** [comment]
> > Hi ratnesh1729, I don't remember exact wallclock times but 1-2 hours could be right. What difference are you interested in? MARS and Market? Since the script trains for a fixed number of iterations the training time should be the same of both datasets.
> 
> @nwojke,hello ,thanks for your excellent work! As you mentioned here the script trains for a fixed number of iterations, what the exactaly iterations it is , I tried to find this parameter in your code, but couldn't found it. I'm training this model on VeRi in on my GPU(TITAN Xp) for like 10 hours but it seems never gonna stop. So I was wondering maybe somewhere went wrong, meanwhile I run train_veri.py, when start training, there is no feedback message, like loss, or iterations occur on the screen. but I looked up the GPU usage, it seems like start training. I want know how long it takes to train on VeRi DataSet. Thank you very much.

you should use tensorboard for monitoring the loss changes.  The training will run indefinitly.

**Comment by sherlockchou86** [comment]
about 17 iterations one second on my 2080ti gpu
