### ISSUE TITLE
validation on MARS

### ISSUE THREAD

**Issue by inakinavarro** [nwojke/cosine_metric_learning#11]
I am trying to validate on MARS but the tips given under Testing on modifying  
 `utils/process_box_features.m` seem not to be enough. The dimensions of the embedding in MARS evaluation are 1024 instead of 128. Do you have a round a modified branch to evaluate the networks trained here?

Thanks!

**Comment by nwojke** [comment]
Isn't the code snippet under Testing a paste of the full file? Computation of cosine similarity /distance shouldn't depend on the actual dimensionality of the feature space. It's just important that both gallery and query have the same dimensionality.

**Comment by nwojke** [comment]
Closing this one because of inactivity.
