### ISSUE TITLE
Unable to understand the significance of the 6 camera views

### ISSUE THREAD

**Issue by DivyanshMalhotra** [nwojke/cosine_metric_learning#13]
Could you please inform the relevance of using 6 cameras? Is it just by coincidence that both the training datasets are using 6 cameras, because I couldn't find their this unique property being used. Also, I wish to train it on my data, which has not been shot in the similar fashion. Is it possible to train it then or not?
Also**, could you please give a description of what do the .mat files contain.** I couldn't decode them so that I could put my data for training.
A read-me file for the gt-query would be appreciated.
Your help would be really appreciated. Thanks

**Comment by nwojke** [comment]
It is just a coincidence that both datasets use 6 cameras (AFAIK, both datasets originate from the same raw data). You may train on a different dataset/problem using this code. In this case, you must write your own dataset adapter (as in ``datasets/mars.py``) and startup script (as in ``train_mars.py``). The mat files used in Market and MARS are dataset-specific. You don't need to care about them if you train on your own data.

**Comment by duyanfang123** [comment]
thank u very much
