### ISSUE TITLE
python train_mars.py --mode=freeze --restore_path=PATH_TO_CHECKPOINT Can anyone tell me what 's the PATH_TO_CHECKPOINT in the upper form ?

### ISSUE THREAD

**Issue by ss199302** [nwojke/cosine_metric_learning#14]
@nwojke   python train_mars.py --mode=freeze --restore_path=PATH_TO_CHECKPOINT
Can anyone tell me what the PATH_TO_CHECKPOINT in the upper form is for?

**Comment by nwojke** [comment]
It is the path to the trained tensorflow model/checkpoint. E.g., ``python train_mars.py --mode=freeze --restore_path=./output/mars/model.ckpt-100000`` for a checkpoint stored after 100000 iterations, assuming you have used the commands in the README for training.

**Comment by ss199302** [comment]
Thank you for your reply, but when I used the finalize derived model for deep_sort, he had the following errors.Thank you for your reply, but when I used the finalize derived ckpt model for deep_sort, he had the following "errors.ValueError: Checkpoint is missing variable [ball/beta]"

**Comment by nwojke** [comment]
Then this seems to be a duplicate of #6. I have started looking into it by re-training a model, but didn't get to test the freezed model in deep sort, yet.

**Comment by nwojke** [comment]
Closing this because of duplication. Re-open if I am wrong.
