### ISSUE TITLE
need help for VeRi model file

### ISSUE THREAD

**Issue by sherlockchou86** [nwojke/cosine_metric_learning#15]
Hello @nwojke ,
Thanks for your work!

As you mentioned [here,](https://github.com/nwojke/cosine_metric_learning/issues/5#issuecomment-381883310), you have trained a model for VeRi DataSet, right?  According to the readme file I cannot get the DataSet from the original owner(nobody reply for my request email), so could you please share me the trained model for VeRi or send me a copy of the DataSet(previous better)?   Thank you very much!

**Comment by sherlockchou86** [comment]
anybody else who owned this model/dataset is appreciated..  thanks!

**Comment by sherlockchou86** [comment]
I have got the dataset from the original owner, close the issue.

**Comment by wduo** [comment]
Hi @sherlockchou86 Could you share the model and dataset with me? I really need these. Many thanks! 931700659@qq.com

**Comment by irisqp** [comment]
> he dataset from the original owner, close the issue.

Hello @sherlockchou86  
Thanks for your work. I'm a student from Xidian University, I've been working on vehicle detection and track lately. Accroding to your reply, I see you got the dataset from the original owner, could you please share me the trained model for VeRi or send me a copy of DataSet? That will be really helpful,  here are my email address irisqp@126.com. Thank you very much!

**Comment by CindyHXH** [comment]
Hi @sherlockchou86 
Could you share the model after training on VeRi dataset? I encountered errors for training with `train_veri.py` and `veri.py`. Thank you very much. I can be reached at hxhcindy@gmail.com

**Comment by hoangtuanvu** [comment]
@sherlockchou86 Could you share the dataset and model with me? Thank you so much. My email address is hoangvu.kstn@gmail.com.

**Comment by Reminding** [comment]
Hello, @sherlockchou86 .Now I'm in the same boat as you, I emailed the owner but didn't get a reply, so I want to ask you for help, can you share me the trained model for VeRi or send me a copy of DataSet? My email address is lhpmemory@163.com . I will appreciate it if you could help me. And @wduo @irisqp @CindyHXH @hoangtuanvu , if the author has sent the model / DataSet to you, can you share it with me? Thank you very much!

**Comment by nwojke** [comment]
I am currently not providing a pre-trained model for VeRi, but if you have access to the dataset you should be able to train a model yourself using the script in branch ``feature/veri_dataset``. Please get in touch with dataset authors and sign their agreeement if you need access to their data.

**Comment by Reminding** [comment]
> I am currently not providing a pre-trained model for VeRi, but if you have access to the dataset you should be able to train a model yourself using the script in branch `feature/veri_dataset`. Please get in touch with dataset authors and sign their agreeement if you need access to their data.

Yes, thank you for you reply and I know it, but the dataset authors didn't reply me, so I'm here for help. I will try to contact the dataset authors again. Thanks!

**Comment by anzy0621** [comment]
Hello, @sherlockchou86 I tried to train the model but faced several issues with the code or my system crashes. Is there any way you could provide me with the pre-trained model on VERI dataset if possible? It would be of great help to my research.  balusuaa@mail.uc.edu

**Comment by quocnhat** [comment]
I can help with the datasets. it is not right to share the link here. please email me at quocnhatute@gmail.com

**Comment by Reminding** [comment]
Thanks you for your help! &nbsp;I have contacted the owner of this dataset and obtained authorization to use it.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "quocnhat"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 下午4:13
收件人: "nwojke/cosine_metric_learning"<cosine_metric_learning@noreply.github.com&gt;; 
抄送: "李华鹏"<1170345157@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [nwojke/cosine_metric_learning] need help for VeRi model file (#15)




I can help with the datasets. it is not right to share the link here. please email me at quocnhatute@gmail.com

**Comment by duyao-art** [comment]
@sherlockchou86 Thanks for your work. Iam working on vehicle detection and track.   Could you please share me the trained model for VeRi or send me a copy of DataSet? That will be really helpful.  Thank you very much!
here are my email address 19059991r@connect.polyu.hk

**Comment by jhonjam** [comment]
@sherlockchou86 Hello, I also have the same problem, I sent an email requesting the data set and they have not given me any response.
Could you share the dataset and model with me? Thank you so much. My email address is  jhonjam@unicauca.edu.co

**Comment by Thanh-Hoo** [comment]
Hi @sherlockchou86 Could you share the dataset and model with me? Thank you so much. My email address is hohdt54@gmail.com

**Comment by sherlockchou86** [comment]
Sorry for the late response. But you need sign their agreement before get the dataset from the **Original Owner** 
I interrupted my work on VeRi and do not have any pre-trained model for that dataset ;(
