### ISSUE TITLE
How to evaluate Market1501 model?

### ISSUE THREAD

**Issue by KeeleyYu** [nwojke/cosine_metric_learning#18]
Does the '--mode=eval' can help evaluate? Cause I did not find  the measure interface in the Market1501 evaluation code ...

Thx a lot if anybody knows how to fix it !

**Comment by KeeleyYu** [comment]
Solutions can be found in comments below the eval_loop.

**Comment by ciwei123** [comment]
@KeeleyYu Hi, just evaluate the model during traing time? using the next "code:CUDA_VISIBLE_DEVICES="" python train_market1501.py \
    --mode=eval \
    --dataset_dir=./Market-1501-v15.09.15/ \
    --loss_mode=cosine-softmax \
    --log_dir=./output/market1501/ \
    --run_id=cosine-softmax \
    --eval_log_dir=./eval_output/market1501"
I don't know how to evaluate it?Thank you very much!!

**Comment by irisqp** [comment]
> 
> 
> Solutions can be found in comments below the eval_loop.

@KeeleyYu Hi, thanks for your work! As you mentioned here 'the solution is below the eval_loop', I coundn't found those comments, can you send me a link or something to help me find solution? Thank you very much!

**Comment by saivenkat-163** [comment]
Hi, I'm trying to export the same files but it's searching for a " query " folder in the market v15 directory. Can you please let me know what that folder is and how I can obtain it. Will be really helpful to me. Thank you.
