### ISSUE TITLE
How can use this code for vehicle counting system

### ISSUE THREAD

**Issue by Akhtar303nu** [nwojke/cosine_metric_learning#22]
I want to count vehicle from video,how can I use deep sort
Thanks

**Comment by nwojke** [comment]
How about

* Set up a detection and tracking system
* Mark/mask an image region for counting
* Whenever an object with an ID which hasn't been counted before passes this image region, increment the counter

Nevertheless, sorry for my late reply. You probably found a way to solve your problem by now. I'll close the issue (as it is also slightly off topic).
