### ISSUE TITLE
Where the author's trained model?

### ISSUE THREAD

**Issue by ciwei123** [nwojke/cosine_metric_learning#27]
where can I find the author's trained model which is not changed to .pb?

**Comment by nwojke** [comment]
Hi ciwei123,

the files are linked in the README.md. The original deep_sort checkpoint files are [here](https://drive.google.com/drive/folders/1m2ebLHB2JThZC8vWGDYEKGsevLssSkjo). Models trained during the re-identification experiments are [here](https://drive.google.com/drive/folders/13HtkxD6ggcrGJLWaUcqgXl2UO6-p4PK0). Both folders contain checkpoint as well as frozen inference graphs.

I hope it helps.
