### ISSUE TITLE
softmargin_triplet_loss

### ISSUE THREAD

**Issue by Phoebe-star** [nwojke/cosine_metric_learning#3]
In losses.py
 line 15 ,  def softmargin_triplet_loss(features, labels, create_summaries=True):
the features are (n,m) ,so the n is batch size and m is dim
but softmargin_triplet_loss is triplet ,the features should be anchor ,positive , negetive  .
but the features are one , why?

and  can you tell me the labels ,it  look like ?

**Comment by nwojke** [comment]
In short, the triplets are generated on the GPU from the current batch. In each iteration, a fixed number of images are sampled for a number of random identities. The rest happens on GPU (therefore also the label array is needed). Sorry for the late response.

**Comment by Phoebe-star** [comment]
the label size is m  , not n, why

**Comment by Phoebe-star** [comment]
thanks, how about the feature and labels  example ?
feature [  [1,1]  [2,2]    [3,3]  [4,4] ]  >> (4,2)      , the [1,1] and [2,2] are the same person
so the label will be  the  [ 1 1 2 2 ] >> (4,)   right ?

**Comment by tonmoyborah** [comment]
If it's tensorboard, the faded line is the actual loss curve and the bold is the smoothed one. Change the smoothing to 0 and you will see.

**Comment by sherlockchou86** [comment]
one batch of images contains anchor, positive, negative samples, according to the labels vectors.
