### ISSUE TITLE
Switching from cpu to gpu error

### ISSUE THREAD

**Issue by ahmedfadhil** [nwojke/cosine_metric_learning#39]
Hi,
I would like to know if it is possible to run the current model on GPU, by simply changing /device:CPU:0 to /device:GPU:0 or there are some further steps to be taken.

PS. I keep getting this error message:

InvalidArgumentError (see above for traceback): Cannot assign a device for operation map/Shape: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available. Registered kernels:...
Could you clarify this point please.
Thank you

**Comment by nwojke** [comment]
* Which device string are you refering to (where in code)? If you have a GPU available, it should be used without any code modifications. Only the preprocessing/data augmentation is placed on CPU and this is a deliberate choice.
* If you need to place code on a specific GPU on a multi-GPU system, I'd suggest using the ``CUDA_VISIBLE_DEVICES`` environment variable.
* If you do encounter GPU problems,  please verify that your TensorFlow installation is good. Does the same explicit device placement work outside of this repository in a small script/minimal example?

**Comment by ahmedfadhil** [comment]
I am refering to the `with tf.device("/device:CPU:0"):` code in the train_app.py. I changed the CPU to GPU, by keeping the rest the same:
I keep getting

_InvalidArgumentError (see above for traceback): Cannot assign a device for operation map/Shape: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available. Registered kernels:..._

**Comment by nwojke** [comment]
Ok, then this is only preprocessing/data augmentation, which is not intended to run on GPU. Preprocessing and data augmentation runs in parallel on the CPU while the GPU is training on preprocessed images.

**Comment by ahmedfadhil** [comment]
In this case should I leave it as cpu and I kindly ask you about what steps to take to train on mars with GPU?
Thank you

**Comment by nwojke** [comment]
I am wondering if your TensorFlow installation is working properly. Did you install ``tensorflow-gpu`` via pip?

It would be great if you check that TensorFlow is using your GPU by following [this guide](https://www.tensorflow.org/guide/using_gpu). The first code snippet should print GPU information if your installation is working.

**Comment by ahmedfadhil** [comment]
Apparently I did not have the GPU installed, I have a docker version that I use to run the models. I will try to install it on the machine. 
Thank you very much

**Comment by nwojke** [comment]
The problem appears to be solved. I am closing the issue.
