### ISSUE TITLE
Changing image shapes to larger dimensions

### ISSUE THREAD

**Issue by ahmedfadhil** [nwojke/cosine_metric_learning#40]
Hi, 
is there a way to change the image dimensions and train on larger images?, if so, could you please elaborate this point and the steps to be taken in this regard. 
Thank you

**Comment by nwojke** [comment]
I *think* you only need to change the shape of the data inside of the functions that read them. I see a couple of hardcoded values [here](https://github.com/nwojke/cosine_metric_learning/blob/master/datasets/market1501.py#L11). I would start by changing them and then deal with any other errors that may occur (changes are good that none).

**Comment by ahmedfadhil** [comment]
That was helpful, thank you

**Comment by nwojke** [comment]
Great, let me know/re-open if you run into errors.
