### ISSUE TITLE
EnqueueError: 'a' must be greater than 0 unless no samples are taken

### ISSUE THREAD

**Issue by ngingihy** [nwojke/cosine_metric_learning#42]
EnqueueError: 'a' must be greater than 0 unless no samples are taken 

When trying to train on my own dataset. My dataset has two folders; test & train. each has a bunch of cropped pictures for my object. When i try to run my own script i get this error

**Comment by ngingihy** [comment]
I also have " Train set size: 0 images, 0 identities"? although the script does read the images.

**Comment by NamrataNyam** [comment]
Hello @ngingihy! Did you get a solution?
If yes how did you resolve it?
