### ISSUE TITLE
When I trained this model  in Market, it took 7 days and was still training. The total file size of the storage space already has 81G. Is this normal?

### ISSUE THREAD

**Issue by gyc521zsc** [nwojke/cosine_metric_learning#51]
When I trained this model  in Market, it took 7 days and was still training. The total file size of the storage space already has 81G. Is this normal?

**Comment by BraginIvan** [comment]
By default, the training is infinite.
Did you look at tensorboard? if losses and metrics are converged, you can stop training by Ctrl+C. It stores checkpoints every several minutes. you can use any of them to create final model, choose one that best on validation, other can be removed.

**Comment by gyc521zsc** [comment]
Thank you very much for your reply.I have a problem now. I have completed the model training, and got query.mat and test.mat.But where is the evaluation code? 
| |
Try to become like
|
|
15769060194@163.com
|
签名由网易邮箱大师定制
On 8/3/2019 19:59，BraginIvan<notifications@github.com> wrote：

By default, the training is infinite.
Did you look at tensorboard? if losses and metrics are converged, you can stop training by Ctrl+C. It stores checkpoints every several minutes. you can use any of them to create final model, choose one that best on validation, other can be removed.

**Comment by gyc521zsc** [comment]
DO you have the Market1501 evaluation code? I need this code to evaluate my model with feat_query.mat and feat_test.mat. Looking forward to your reply.


| |
15769060194
|
|
邮箱：15769060194@163.com
|

签名由 网易邮箱大师 定制

On 08/03/2019 20:11, Persistent & 努力 wrote:
Thank you very much for your reply.I have a problem now. I have completed the model training, and got query.mat and test.mat.But where is the evaluation code? 
| |
Try to become like
|
|
15769060194@163.com
|
签名由网易邮箱大师定制
On 8/3/2019 19:59，BraginIvan<notifications@github.com> wrote：

By default, the training is infinite.
Did you look at tensorboard? if losses and metrics are converged, you can stop training by Ctrl+C. It stores checkpoints every several minutes. you can use any of them to create final model, choose one that best on validation, other can be removed.
