### ISSUE TITLE
Training on my own dataset caused error

### ISSUE THREAD

**Issue by segawasai** [nwojke/cosine_metric_learning#54]
EnqueueError: Cannot feed value of shape (128, 128, 256, 3) for Tensor 'Placeholder_1:0', which has shape '(?,)'
C:\Users\Trungtdd\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\summary\writer\writer.py:386: UserWarning: Attempting to use a closed FileWriter. The operation will be a noop unless the FileWriter is explicitly reopened.
  warnings.warn("Attempting to use a closed FileWriter. "

**Comment by duyao-art** [comment]
@segawasai Hello, I got the same warning issue when I tried to re-train the cosine matrix learning codes using VeRi dataset. Did you solve this problem? Could you please give me some advice?

**Comment by theonlyNischal** [comment]
@segawasai  @duyao-art @nwojke Any update on this issue? I am also facing the same issue on working with VeRi dataset.
