### ISSUE TITLE
How to train a model when tracking a vehicle？

### ISSUE THREAD

**Issue by tensorflowt** [nwojke/cosine_metric_learning#57]
Hi,nwojke!

Currently I need to track multiple vehicles and pedestrians.
And how do I train the deep sort model for this task？

**Comment by yanfg1** [comment]
hello ,I have met this problem too,have you solve this problem?

**Comment by hghimanshu** [comment]
For vehicle tracking you can use VeRI dataset.

**Comment by tensorflowt** [comment]
thank you
