### ISSUE TITLE
how to produce query-feature-mat gallery-feature-mat on market1501 dataset ?

### ISSUE THREAD

**Issue by Lucky466** [nwojke/cosine_metric_learning#59]
when i use export mode to generate feat_query.mat and feat_test.mat,query-feature-mat has 3368128,while gallery-feature-mat has 19732*128dims,when use market1501 evalution master ,the matrix use multiple,error using *

The internal matrix dimensions must be consistent.
error sqdist (line 20)
m = repmat(qmag, pn, 1) + repmat(pmag', 1, qn) - 2*p'*q;

error market_evaluation (line 86)
dist = sqdist(Hist_test, Hist_query); % distance calculate with single query. Note that Euclidean distance is
equivalent to cosine distance if vectors are l2-normalized

looking forward to your reply!
thank u

**Comment by tiberium24** [comment]
how did you solve this??

**Comment by Lucky466** [comment]
in the main code, status"fianalize"or some other status, I remember not clearly,pleade check status in the main code, hope to help u


 
---Original---

**Comment by tiberium24** [comment]
Thanks for your quick response. I am not sure what you are referring to. 
The dimensions of 'repmat(qmag, pn, 1)' are 128,128
the dimensions of 'p' are 19732,128
and the dimensions of 'q' are 3368,128
Therefore no matter how are tweak the multiplication the mismatch is between 19732 and 3368.

**Comment by Lucky466** [comment]
you can step to the breakpoint,then try to change the transpose of p,q,may be others


 
---Original---

**Comment by tiberium24** [comment]
definitely the problem is in the dimensions of p and q. I am not very familiar with the process in the code and I merely want to evaluate so I am not sure which change is that that you suggest. I tried this:
m = repmat(qmag, pn, 1) + repmat(pmag', 1, qn) - 2*p(1:3368,:)'*q;

It works but mAP=0, basically I shouldnt be doing this. I would appreciate your help. Thanks a lot again.

**Comment by saivenkat-163** [comment]
Hi, I'm trying to export the same files but it's searching for a " query " folder in the market v15 directory. Can you please let me know what that folder is and how I can obtain it. Will be really helpful to me. Thank you.
