### ISSUE TITLE
ValueError: Checkpoint is missing variable [ball/beta]

### ISSUE THREAD

**Issue by KeeleyYu** [nwojke/cosine_metric_learning#6]
Hi, nwojke

I want to generate the trained model and use it for deep-sort, but I have a trouble here. 

At first the following command is used to to generate the model.ckpt:

`'python train_market1501.py  --dataset_dir=./Market-1501-v15.09.15/  --loss_mode=cosine-softmax  --log_dir=./output/market1501/  --run_id=cosine-softmax'`  

After a few iterations, I interrupted it and used the following command to generate the detections.npy:

`'python generate_detections.py --mot_dir=./MOT16/train --model=./model.ckpt'`

However, I got this ERROR:

> Traceback (most recent call last):
>   File "generate_detections_V2.py", line 474, in <module>
>     f = create_box_encoder(args.model, batch_size=32, loss_mode=args.loss_mode)
>   File "generate_detections_V2.py", line 363, in create_box_encoder
>     image_encoder = create_image_encoder(model_filename, batch_size, loss_mode)
>   File "generate_detections_V2.py", line 358, in create_image_encoder
>     model_filename, loss_mode)
>   File "generate_detections_V2.py", line 337, in _create_image_encoder
>     checkpoint_path, slim.get_variables_to_restore())
>   File "E:\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 612, in assign_from_checkpoint
>     raise ValueError(log_str)
> ValueError: Checkpoint is missing variable [ball/beta]

(I did a few changes in generate_detections_V2.py but nothing to do with the network..)
Could you please show me how to fix it ? Thanks a lot!

**Comment by Clara85** [comment]
Does this has anything to do with the tensorflow version? What's the version requirement of tensorflow? @KeeleyYu @MingjieLiu

**Comment by MingjieLiu** [comment]
the version of tensorflow should be >=1.0

**Comment by nwojke** [comment]
Can you try to export the model and use the frozen inference graph as described [here](https://github.com/nwojke/cosine_metric_learning#model-export)?

**Comment by nwojke** [comment]
Are you using the same python and tensorflow version for training and deep_sort? [This issue](https://github.com/tensorflow/models/issues/2675) seems to be related.

**Comment by KeeleyYu** [comment]
My python version is `3.6.4 with Anaconda`.
My tensorflow version is `1.6.0`.

I checked the issue you mentioned and I did some changes to `freeze` function in `train_app.py`, like:
`        '''
        saver = tf.train.Saver(slim.get_variables_to_restore())
        saver.restore(session, checkpoint_path)
        '''
        
        session.run(tf.initialize_all_variables())
        saver = tf.train.Saver(write_version = saver_pb2.SaverDef.V1)
        saver.save(session, checkpoint_path)`

However, it didn't work as well. 
So, what python and tensorflow version should be used? I didn't notice there were any requirements...
@nwojke

**Comment by nwojke** [comment]
@KeeleyYu I think I have used 1.4.1 when I have last tested it. Also, can you try passing an absolute path to the checkpoint file?

It might take some time before I can look into this, sorry.

**Comment by KeeleyYu** [comment]
I pass the absolute path to the checkpoint file yet still cannot works...
Hope you can figure it out :)

**Comment by ss199302** [comment]
@KeeleyYu   Do you solve this problem? I have the same problem with you. I train myself to produce three weight files, and the official weight file is two. Is it related to this?

**Comment by MingjieLiu** [comment]
I build themodel by myself and use it for training and testing or extracting the features




| |
刘明杰
邮箱：lkj_lmj@163.com
|

签名由 网易邮箱大师 定制

On 08/18/2018 22:18, ss199302 wrote:

@KeeleyYu Do you solve this problem? I have the same problem with you. I train myself to produce three weight files, and the official weight file is two. Is it related to this?

**Comment by nwojke** [comment]
I have been re-testing the generation of deep sort detections using a model trained on Market 1501 and I cannot reproduce the error. When you execute
```
 python generate_detections_V2.py --mot_dir=./MOT16/train --model=./market1501.pb
```
which file is this generate_detection_V2.py refering to? In your backtrace I see 
```
File "generate_detections_V2.py", line 337, in _create_image_encoder
checkpoint_path, slim.get_variables_to_restore())
```
but this doesn't seem to correspond with the current file version [here](https://github.com/nwojke/deep_sort/blob/master/tools/generate_detections.py)? The entire file has only 213 lines.

**Comment by ss199302** [comment]
@nwojke    thanks your reply!   it is ok.

**Comment by nwojke** [comment]
Seems to be solved.

**Comment by KeeleyYu** [comment]
Yes, it has been solved for now!
The main reason is that I didn't update the code from your repository...
Thanks for your reply.
@nwojke

**Comment by ciwei123** [comment]
@KeeleyYu 　Hi，I have trained model about Market-1501, but I don't know how to evaluate the model,could you tell me ?Thank you very much!
