### ISSUE TITLE
Export model trained on Market1501 for Deep_sort ?

### ISSUE THREAD

**Issue by mazatov** [nwojke/cosine_metric_learning#62]
I see how to export the model to Deep_Sort trained on Mars dataset. Is it possible to do the same for Market dataset. I'd like to compare performance. 

Thanks!

**Comment by mazatov** [comment]
I think I figured this out, PATH_TO_CHECKPOINT should not have any extension so something like this : 
model.ckpt-354924

**Comment by saivenkat-163** [comment]
Hi, I'm trying to export the same files but it's searching for a " query " folder in the market v15 directory. Can you please let me know what that folder is and how I can obtain it. Will be really helpful to me. Thank you.
