### ISSUE TITLE
where is Market-1501_baseline-v16.01.14 file ?

### ISSUE THREAD

**Issue by cervantes-loves-ai** [nwojke/cosine_metric_learning#7]
after successfully training, when i try to test than i noticed that  sdk directory as well as Market-1501_baseline-v16.01.14 file is missing.. any solutions ?

**Comment by aymane6** [comment]
https://drive.google.com/file/d/0B8-rUzbwVRk0c054eEozWG9COHM/view

**Comment by ss199302** [comment]
Hello, after opening this website, I found it was not this Market-1501_baseline-v16.01.14 file?WHY?

**Comment by nwojke** [comment]
Please refer to the [dataset website](http://www.liangzheng.org/Project/project_reid.html) for the evaluation software. There you find a link to the evaluation software in section Baseline Codes -> Performance Evaluation.

**Comment by ss199302** [comment]
thanks!

**Comment by ciwei123** [comment]
@ss199302 @nwojke Hi, this code just for ' single query' of evaluation? And how to create 'Hist_query_max.mat' which is used in Market-1501_baseline-v16.01.1 ? Thank you very much!

**Comment by JIALIUZHOU** [comment]
You do not need to find the file 'Market-1501_baseline-v16.01.14', but to create your own 'feat_query.mat' and 'feat_test.mat'. You only need to create a new folder

**Comment by gyc521zsc** [comment]
> You do not need to find the file 'Market-1501_baseline-v16.01.14', but to create your own 'feat_query.mat' and 'feat_test.mat'. You only need to create a new folder

Thank you for your answer, but I don’t understand it.I need to creat a new folder ,its name is  Market-1501_baseline-v16.01.14. And how to test Market-1501.
python train_market1501.py \
    --mode=export \
    --dataset_dir=./Market-1501-v15.09.15/
    --sdk_dir=./Market-1501_baseline-v16.01.14/
    --loss_mode=cosine-softmax \
    --restore_path=PATH_TO_CHECKPOINT
I can't understand it ,it dosen't work.

**Comment by JIALIUZHOU** [comment]
Thank you very much. I have just solved it.







------------------ Original ------------------

**Comment by gyc521zsc** [comment]
> thanks!

Did you solve this problem?  Can you tell me?

**Comment by JIALIUZHOU** [comment]
Yeah, I just used the mode in the code to get feat.mat then used it in an evaluation Matlab code repository. But the website or the file is in my office. If you really need it, could I send it to you on Monday?

发自我的iPhone


------------------ Original ------------------

**Comment by JIALIUZHOU** [comment]
Oh, sorry. I may be something wrong and do not understand your problem. Do you mean that you cannot get the feature.mat? The using mode is ‘export’  and the restore_path should be your trained model.ckpt-(some number). Just use it and if you have other problems or cannot solve it, please contact with me. Good luck!



发自我的iPhone


------------------ Original ------------------

**Comment by saivenkat-163** [comment]
@JIALIUZHOU, I'm trying to export the .mat files after training but it's searching for a " query " folder in the market v15 directory. Can you please let me know what that folder is and how I can obtain it? Will be really helpful to me. Thank you.

**Comment by QibingJiang** [comment]
> @JIALIUZHOU, I'm trying to export the .mat files after training but it's searching for a " query " folder in the market v15 directory. Can you please let me know what that folder is and how I can obtain it? Will be really helpful to me. Thank you.

I think you are using the following command:
python train_market1501.py \
    --mode=export \
    --dataset_dir=./Market-1501-v15.09.15/
    --sdk_dir=./Market-1501_baseline-v16.01.14/
    --loss_mode=cosine-softmax \
    --restore_path=PATH_TO_CHECKPOINT

Did you replace PATH_TO_CHECKPOINT with your own checkpoint path. For example: ./output/market1501/cosine-softmax/model.ckpt-703901
