### ISSUE TITLE
whats is the input node and output node?

### ISSUE THREAD

**Issue by qiaoshh** [nwojke/cosine_metric_learning#73]
Hi, thanks for your great working! now, i have trained my own dateset same as MARS, with finishing the  train, i try to convert the trained files(*.index, *.meta, *.data, *.pbtxt) to *.pb, the question is how can i confirm the input node and output node's name, anybody can help me? Regards

**Comment by kbegiedza** [comment]
@qiaoshh Did you find input / output name and format?
