### ISSUE TITLE
training the model with my own data

### ISSUE THREAD

**Issue by aymane6** [nwojke/cosine_metric_learning#9]
precated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Train set size: 58 images, 21 identities
feature dimensionality:  128
WARNING:tensorflow:From C:\tensorflow1\cosine_metric_learning-master\nets\deep_sort\network_definition.py:84: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
WARNING:tensorflow:From C:\tensorflow1\cosine_metric_learning-master\train_app.py:615: sparse_softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.sparse_softmax_cross_entropy instead. Note that the order of the logits and labels arguments has been changed.
WARNING:tensorflow:From C:\Users\ayman\Anaconda3\envs\py35\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:433: compute_weighted_loss (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.compute_weighted_loss instead.
WARNING:tensorflow:From C:\Users\ayman\Anaconda3\envs\py35\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:146: add_arg_scope.<locals>.func_with_args (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.add_loss instead.
---------------------------------------
Run ID:  cosine-softmax
Log directory:  ./output/market1501/cosine-softmax
---------------------------------------
WARNING:tensorflow:From C:\Users\ayman\Anaconda3\envs\py35\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py:736: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-05-28 15:10:18.081763: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-05-28 15:10:18.646344: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1356] Found device 0 with properties:
name: GeForce 940MX major: 5 minor: 0 memoryClockRate(GHz): 1.2415
pciBusID: 0000:01:00.0
totalMemory: 2.00GiB freeMemory: 1.66GiB
2018-05-28 15:10:18.651127: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1435] Adding visible gpu devices: 0
2018-05-28 15:10:19.266360: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-28 15:10:19.268433: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:929]      0
2018-05-28 15:10:19.270037: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:942] 0:   N
2018-05-28 15:10:19.271564: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1430 MB memory) -> physical GPU (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0, compute capability: 5.0)
EnqueueError: Cannot take a larger sample than population when 'replace=False'

can you help me please fixing this problem. cause i am new in deeplearning and python and all that stuff.

**Comment by nwojke** [comment]
I have seen the error ``EnqueueError: Cannot take a larger sample than population when 'replace=False'`` happen when the number of identities were less than the number of identities to be enqueued in each batch. Is this training or evaluation? Anyways, this shouldn't happen and I guess something is wrong with the training data. The script prints the number of identities in the training data [here](https://github.com/nwojke/cosine_metric_learning/blob/master/train_market1501.py#L58). What is the output?

**Comment by nwojke** [comment]
Closing this one due to inactivity.

**Comment by JakeCowton** [comment]
For anyone coming across this, it became a non-issue once I set the image size correctly.

**Comment by ZRSlayee** [comment]
I have met this error too. Have u solved it?

**Comment by ngingihy** [comment]
what about that enqueue error?
EnqueueError: 'a' must be greater than 0 unless no samples are taken

**Comment by ngingihy** [comment]
> I have seen the error `EnqueueError: Cannot take a larger sample than population when 'replace=False'` happen when the number of identities were less than the number of identities to be enqueued in each batch. Is this training or evaluation? Anyways, this shouldn't happen and I guess something is wrong with the training data. The script prints the number of identities in the training data [here](https://github.com/nwojke/cosine_metric_learning/blob/master/train_market1501.py#L58). What is the output?

Train set size: 14 images, 6 identities

**Comment by taosean** [comment]
> > I have seen the error `EnqueueError: Cannot take a larger sample than population when 'replace=False'` happen when the number of identities were less than the number of identities to be enqueued in each batch. Is this training or evaluation? Anyways, this shouldn't happen and I guess something is wrong with the training data. The script prints the number of identities in the training data [here](https://github.com/nwojke/cosine_metric_learning/blob/master/train_market1501.py#L58). What is the output?
> 
> Train set size: 14 images, 6 identities

I can confirm what @nwojke said is correct. 
`the number of identities to be enqueued in each batch` is calculated as `batch_size /  num_images_per_id`, please see the description [here](https://github.com/nwojke/cosine_metric_learning/blob/eda0daaa5462c61ac44553f2151070fd7e316cc8/train_app.py#L135).

**Comment by nwojke** [comment]
@ngingihy As pointed out by @taosean, you could change the batch size and number of images per identity to make the error go away, but I am not sure that you have enough data to train a new model.
